#! /bin/bash

# make sure that we can cd into dist folder
currentDir=$(pwd)
# echo ${currentDir}
searchString="fullstack/nightwatch"
began=${currentDir%$searchString*}
rest=${currentDir#*$searchString}
dodo=${currentDir/$searchString/DODO}
if [[ "${rest}" == "" ]] && [[ "${dodo}" == "${began}DODO" ]]; then
  cd dist
  rm -rfRv ./*
  
else
  echo "please run from root dir fullstack/nightwatch"
  exit -1
fi
# echo rootDir: ${rootDir}